name: protos
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0-63.1.beta

# Add regular dependencies here.
dependencies:
  grpc: ^3.1.0
  protobuf: ^2.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^5.0.0+1

